# Generated by Django 5.1.5 on 2025-01-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=255)),
                ('work_color', models.CharField(max_length=255)),
                ('work_pic', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
